[tool.black]
line_length = 100

[tool.isort]
known_first_party = "flight_mailer"
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = false
skip = [".git", "venv"]
